using NUnit.Framework;

[TestFixture]
public class TestClass : TestClassBase
{
    [TestCase(0, "Zero")]
    [TestCase(1, "One")]
    [TestCase(2, "Two")]
    [TestCase(3, "Three")]
    [TestCase(4, "Four")]
    [TestCase(5, "Five")]
    [TestCase(6, "Six")]
    [TestCase(7, "Seven")]
    [TestCase(8, "Eight")]
    [TestCase(9, "Nine")]
    [TestCase(10, "Ten")]
    [TestCase(11, "Eleven")]
    [TestCase(12, "Twelve")]
    [TestCase(13, "Thirteen")]
    [TestCase(14, "Fourteen")]
    [TestCase(15, "Fifteen")]
    [TestCase(16, "Sixteen")]
    [TestCase(17, "Seventeen")]
    [TestCase(18, "Eighteen")]
    [TestCase(19, "Nineteen")]
    [TestCase(20, "Twenty")]
    [TestCase(21, "Twenty One")]
    [TestCase(22, "Twenty Two")]
    [TestCase(23, "Twenty Three")]
    [TestCase(24, "Twenty Four")]
    [TestCase(25, "Twenty Five")]
    [TestCase(26, "Twenty Six")]
    [TestCase(27, "Twenty Seven")]
    [TestCase(28, "Twenty Eight")]
    [TestCase(29, "Twenty Nine")]
    [TestCase(30, "Thirty")]
    [TestCase(31, "Thirty One")]
    [TestCase(32, "Thirty Two")]
    [TestCase(33, "Thirty Three")]
    [TestCase(34, "Thirty Four")]
    [TestCase(35, "Thirty Five")]
    [TestCase(36, "Thirty Six")]
    [TestCase(37, "Thirty Seven")]
    [TestCase(38, "Thirty Eight")]
    [TestCase(39, "Thirty Nine")]
    [TestCase(40, "Forty")]
    [TestCase(41, "Forty One")]
    [TestCase(42, "Forty Two")]
    [TestCase(43, "Forty Three")]
    [TestCase(44, "Forty Four")]
    [TestCase(45, "Forty Five")]
    [TestCase(46, "Forty Six")]
    [TestCase(47, "Forty Seven")]
    [TestCase(48, "Forty Eight")]
    [TestCase(49, "Forty Nine")]
    [TestCase(50, "Fifty")]
    [TestCase(51, "Fifty One")]
    [TestCase(52, "Fifty Two")]
    [TestCase(53, "Fifty Three")]
    [TestCase(54, "Fifty Four")]
    [TestCase(55, "Fifty Five")]
    [TestCase(56, "Fifty Six")]
    [TestCase(57, "Fifty Seven")]
    [TestCase(58, "Fifty Eight")]
    [TestCase(59, "Fifty Nine")]
    [TestCase(60, "Sixty")]
    [TestCase(61, "Sixty One")]
    [TestCase(62, "Sixty Two")]
    [TestCase(63, "Sixty Three")]
    [TestCase(64, "Sixty Four")]
    [TestCase(65, "Sixty Five")]
    [TestCase(66, "Sixty Six")]
    [TestCase(67, "Sixty Seven")]
    [TestCase(68, "Sixty Eight")]
    [TestCase(69, "Sixty Nine")]
    [TestCase(70, "Seventy")]
    [TestCase(71, "Seventy One")]
    [TestCase(72, "Seventy Two")]
    [TestCase(73, "Seventy Three")]
    [TestCase(74, "Seventy Four")]
    [TestCase(75, "Seventy Five")]
    [TestCase(76, "Seventy Six")]
    [TestCase(77, "Seventy Seven")]
    [TestCase(78, "Seventy Eight")]
    [TestCase(79, "Seventy Nine")]
    [TestCase(80, "Eighty")]
    [TestCase(81, "Eighty One")]
    [TestCase(82, "Eighty Two")]
    [TestCase(83, "Eighty Three")]
    [TestCase(84, "Eighty Four")]
    [TestCase(85, "Eighty Five")]
    [TestCase(86, "Eighty Six")]
    [TestCase(87, "Eighty Seven")]
    [TestCase(88, "Eighty Eight")]
    [TestCase(89, "Eighty Nine")]
    [TestCase(90, "Ninety")]
    [TestCase(91, "Ninety One")]
    [TestCase(92, "Ninety Two")]
    [TestCase(93, "Ninety Three")]
    [TestCase(94, "Ninety Four")]
    [TestCase(95, "Ninety Five")]
    [TestCase(96, "Ninety Six")]
    [TestCase(97, "Ninety Seven")]
    [TestCase(98, "Ninety Eight")]
    [TestCase(99, "Ninety Nine")]
    [TestCase(100, "One Hundred")]
    [TestCase(101, "One Hundred One")]
    [TestCase(110, "One Hundred Ten")]
    [TestCase(111, "One Hundred Eleven")]
    [TestCase(123, "One Hundred Twenty Three")]
    [TestCase(1000, "One Thousand")]
    [TestCase(1001, "One Thousand One")]
    [TestCase(1010, "One Thousand Ten")]
    [TestCase(1011, "One Thousand Eleven")]
    [TestCase(12345, "Twelve Thousand Three Hundred Forty Five")]
    [TestCase(1234567, "One Million Two Hundred Thirty Four Thousand Five Hundred Sixty Seven")]
    [TestCase(1234567890, "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety")]
    [TestCase(1000000000, "One Billion")]
    [TestCase(1000000001, "One Billion One")]
    [TestCase(1000000100, "One Billion One Hundred")]
    [TestCase(1000001000, "One Billion One Thousand")]
    [TestCase(1000100000, "One Billion One Hundred Thousand")]
    public void TestMethod(int num, string expectedOutput)
    {
        Assert.AreEqual(expectedOutput, new Solution().NumberToWords(num));
    }
}